name: Multi cluster; two pairs of clusters on two isolated networks

on:
  [workflow_dispatch, push]
jobs:
  k3d-multicluster-demo:
    name: Two pairs of clusters on two isolated networks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: test-cluster-1-a
        name: "Create 1st k3d Cluster in 172.18.0.0/16"
        with:
          cluster-name: "test-cluster-1-a"
          args: --config=.github/workflows/assets/1.yaml

      - uses: ./
        id: test-cluster-1-b
        name: "Create 2nd k3d Cluster in 172.18.0.0/24"
        with:
          cluster-name: "test-cluster-2-a"
          args: --config=.github/workflows/assets/3.yaml

      - uses: ./
        id: test-cluster-2-a
        name: "Create 1st k3d Cluster in 172.19.0.0/24"
        with:
          cluster-name: "test-cluster-1-b"
          args: --config=.github/workflows/assets/2.yaml

      - uses: ./
        id: test-cluster-2-b
        name: "Create 2nd k3d Cluster in 172.19.0.0/24"
        with:
          args: --config=.github/workflows/assets/4.yaml

      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-test-cluster-1-a
          kubectl cluster-info --context k3d-test-cluster-2-a
          kubectl cluster-info --context k3d-test-cluster-1-b
          kubectl cluster-info --context k3d-test-cluster-2-b

      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1-a
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-1-b
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-2-a
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-2-b
          kubectl get nodes -o wide

      - name: Network
        run: |
          docker network list
          docker network inspect nw01
          docker network inspect nw02
